wesbos/es6-articles

01-var-scoping-refresher-draft2.md, 02-let-vs-const-draft.md, 03-let-and-const-in-the-real-world-draft.md
=> articles 1 2 3

.gitignore, 04 - Temporal Dead Zone.md
Sounds spookier than it is.  👻
=> Temporal Dead Zone

08 - Arrow Functions and this.md
@wesbos My IDE kept crying about the JS here. Would you be able to take a quick look at the code blocks for accuracy to make sure that my linter is just being a baby? 👶
If it's not the case, and revisions are needed, lemme know.
=> one last one

09 - Default Function Arguments.md, 10 - When NOT to use an Arrow Function.md, 12 - Template Strings Introduction.md
=> Lessons 9, 10, 12

13 - Creating HTML fragments with Template Literals.md, 14 - Tagged Template Literals.md, 16 - Santizing User Data with Tagged Templates.md, 17 - Additional String Improvements.md
That last joke is a real groaner.
=> pow! sock! biff!

10 - When NOT to use an Arrow Function.md
=> Fix invalid HTML :kissing_heart:

24 - Using for of with Objects.md, 25 - Array.from() and Array.of().md, 26 - Array. find() and .findIndex().md, 27 - Array .some() and .every().md
=> Videos 24-27

22 - The for of loop.md, 23 - The for of Loop in Action.md
The video titles are a little mixed up in the zips. You might want to take a look.
=> Twice On Sunday

36 - Chaining Promises + Flow Control.md, 37 - Working with Multiple Promises.md, 39 - Getting Started with ESLint.md
=> 36, 37, 39

40 - Airbnb ESLint Settings.md
Just one article today...
But it's the end of Part 2! 🔥
=> Article 40

48 - Tool-Free Modules with SystemJS (+bonus BrowserSync setup).md
=> Update jan 8

17 - Additional String Improvements.md
Haven't seen the video but fixed leftPad function which didn't work, and some formatting
=> fixed leftPad function and a few formatting issues

breakout-email.md
Corrects a few spelling typos and grammar.
=> update spelling and grammar

22 - The for of loop.md
Little code examples adjustments
=> Update 22 - The for of loop.md

03.1 - Block Scope is the new IIFE.md
Fixes:
- Wrong use of Immediately-Invoked Function Expression
- Multiple typo instances of IIFE
- Other random grammar errors
=> Update 03.1 - Block Scope is the new IIFE.md

19 - Destructing Arrays.md
Hey Wes, thanks for the articles, just fixed some typos. Will see if I can find more of them as I continue reading it. Cheers
=> Typo fixed

09 - Default Function Arguments.md
=> Update 09 - Default Function Arguments.md

30 - More Spread Examples.md
Few more fixes for missing variable on the console.log in the examples
=> Added missing variable in the example

61 - Sets and WeakSets.md
=> Pass an iterable to `Set` constructor

13 - Creating HTML fragments with Template Literals.md
=> Update 13 - Creating HTML fragments with Template Literals.md

02 - let VS const.md
Changed a few minor things with spacing. Added a small bit of description to what curly brackets are.
Woo #hacktoberfest!
Issue #64
=> 📝 Review of Article 02.

26 - Array. find() and .findIndex().md
This is for the .findIndex post. Listened to syntax right before this!
=> Review basic grammar, including run-ons, and code syntax highlighting

04 - Temporal Dead Zone.md
Fixed typos
Cleared up explanation language
=> 04 - Corrected typos and unclear wording

10 - When NOT to use an Arrow Function.md
Adjusted consistency across the article with language use
Refined wording that was unclear
Corrected grammar and spelling errors
=> 10 - Clarity and typo correction

16 - Santizing User Data with Tagged Templates.md
=> Update 16 - Santizing User Data with Tagged Templates.md

03.2 - let and for loops in JavaScript.md
03.2 - let and for loops in javascript.
Hope this helps! :)
=> Made some small grammar and phrasing updates to help with clarity.

06 - Arrow Functions Introduction.md
=> Cleanup punctuation and inconsistencies

12 - Template Strings Introduction.md
Updated Grammar based on Grammarly check
=> Update 12 - Template Strings Introduction.md

14 - Tagged Template Literals.md
=> Fix typo in article 14
